language: python
python:
- '2.7'
- '3.3'
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
- pip install coverage
script:
- python -m unittest discover -v ./ci_play/
- coverage run ./ci_play/test.py
after_success:
- codecov --token=1f553b68-5925-4d60-a6e4-1e7178bd674b
deploy:
  provider: s3
  access_key_id: AKIAJSCVAIOGLYTAGWXA
  secret_access_key:
    secure: SU718t+IQkaivPhlYJrsfvaQrl3kImpLpFQY09XsukRoHjbpzP8QQkoFgWQky7O7GF1ouzLhVzR9Q43q+CxyxZkpqMyipxGHR3HjYOWi+8QKBgyFEX1cT3Hmg/nyvzjRgFPE96ns4u5YbVlC6MLdAG5zG/7qCdiwwBoFd/2Xf6wHQjE14EyN9T2Knii9TbKBg1nB+nD4Nj5EEhPqCHWHBCuVeKYWIKF7dblZl84TQxM7b3c4iDnf0pLy5fG31RpZcCziLoSnSDGRJxwKCXPFeDCEXy+wh33WBnD1PhiCKk0/1hsp8+B/ikHFNoZ0CXlrrwr7XB/sg8yBoVViOt++S0IfJguYXycmGUGZZtEMSbsSB/DXrlFwzLCIHqVVfLPjbuavo1QH7wIqB8RGWARbhoqS9Wtn9mjB5YVX3QBHdYvhLFxObiE+tytY+M9R81it0XVpf6rq7QUWmJ0hzMR1Z+xNp/Fh95bNEbdy3eOSGGsXR0zbkZF/IxTImNE29hHF8PPSm867VTwpwqMlJ05z84w5PC6pG35ytEym1TsmfbtXy29wN0lDBD1Fk6hCJ216FSAz6BE5zJlCXs3dM29harficsSM/YFIw3lCyJ0qeXy1IACsdM03tI9qYUdI1W7VHqels6ZPt45fwZW2nRKVpU2kmWARK1MCbqAhKjwpbO4=
  bucket: buggythestudent.com
  local-dir: s3_play
  acl: 'public_read'
  on:
    repo: buggythestudent/travis
